### ISSUE TITLE
How is it work ?

### ISSUE THREAD

**Issue by aziemhelmi** [JamieDavidson/PUBGMobileConfigDecrypter#1]
can u teach me how to use it

**Comment by JamieDavidson** [comment]
If you download the initial release from [here](https://github.com/JamieDavidson/PUBGMobileConfigDecrypter/releases) it contains everything you need.  This is a command line tool, which means you don't just click and run it, you use it through command prompt.

Extract the release folder and open it. Hold shift and then right click inside the folder, select "Open command prompt here". From there, follow the instructions in the README for encrypting or decrypting the file. A copy of the latest version of UserCustom.ini is included in the release.

**Comment by aziemhelmi** [comment]
thanks sir, i just place your file UserCustom.ini file to my game folder,
just to see a different. i appreciate your help

**Comment by aziemhelmi** [comment]
Hello there,

I just signed the petition "Government of Malaysia: Smoking Ban in All
Eateries in Malaysia" and wanted to see if you could help by adding your
name.

Our goal is to reach 300,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/FQYrFYXFxJ

Thanks!
Mohd Khazim Helmi
